<?php
$con=mysql_connect("localhost","root","hanaa12300");

mysql_select_db("readme");

$q=mysql_query("select * from bookinfo");
include('session.php');
require_once "./classes/pbook.php";
$counter=1;
print "<!DOCTYPE html>\n";
print "<html lang=\"en\">\n";
print "\n";
print "<head>\n";
print "  <meta charset=\"utf-8\">\n";
print "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
print "  <meta name=\"description\" content=\"\">\n";
print "  <meta name=\"author\" content=\"\">\n";
print "\n";
print "  <title>Read Me</title>	\n";
print "  <!-- Bootstrap Core CSS -->\n";
print "  <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\n";
print "\n";
print "  <!-- Fonts -->\n";
print "  <link href=\"font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n";
print "  <link href=\"css/animate.css\" rel=\"stylesheet\" />\n";
print "  <!-- Squad theme CSS -->\n";
print "  <link href=\"css/style.css\" rel=\"stylesheet\">\n";
//print "  <link href=\"color/default.css\" rel=\"stylesheet\">\n";
print "   <link href=\"color/index1.css\" rel=\"stylesheet\">\n";
print "</head>\n";
print "\n";
print "<body id=\"page-top\" data-spy=\"scroll\" data-target=\".navbar-custom\">\n";

print "\n";
print "  <nav class=\"navbar navbar-custom navbar-fixed-top\" role=\"navigation\">\n";
print "    <div class=\"container\">\n";
print "      <div class=\"navbar-header page-scroll\">\n";
print "        <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-main-collapse\">\n";
print "                    <i class=\"fa fa-bars\">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </i>\n";
print "                </button>\n";
print "        <a class=\"navbar-brand\" href=\"index1.html\">\n";
print "          <h1>Read Me</h1>";
print "        </a>\n";
//echo $login_session;
print "      </div>\n";


print "\n";
print "    <!-- Collect the nav links, forms, and other content for toggling -->\n";
print "	   <div class=\"collapse navbar-collapse navbar-right navbar-main-collapse\">\n";
print "	      <ul class=\"nav navbar-nav\">\n";
print "          <li class=\"active\"><a href=\"#intro\">Home</a></li>\n";
print "          <li class=\"dropdown\">\n";
print "            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Categories <b class=\"caret\"></b></a>\n";
print "			\n";
print "            <ul class=\"dropdown-menu\">\n";
print "              <li><a href=\"#Fiction\">Fiction</a></li>\n";
print "			  <li><a href=\"#Kids\">Kids</a></li>\n";
print "			  <li><a href=\"#History\">History</a></li>\n";
print "			  <li><a href=\"#Horror\">Horror</a></li>\n";
print "			  <li><a href=\"#Romance\">Romance</a></li>\n";
print "			  <li><a href=\"#Arts\">Arts</a></li>\n";
print "\n";
print "            </ul>\n";
print "          </li>\n";
print "		   <li><a href=\"Login_v6/index.html\">Admin</a></li>\n";
print "		    <li><a href=\"LogOut.php\">Log Out</a></li>\n";
print "        </ul>";
print "      <!-- /.navbar-collapse -->\n";
print "    </div>\n";
print "    <!-- /.container -->\n";
print "  </nav>\n";
print "\n";
print "  <!-- Section: intro -->\n";
print "  <section id=\"intro\" class=\"intro\">\n";
print "\n";
print "    <div class=\"slogan\">\n";
print "      <h2>WELCOME TO <span class=\"text_color\">Read Me</span> </h2>\n";
print "      <h4>We provide to you a fantastic collection of different types of books</h4>\n";
print "    </div>\n";
print "    <div class=\"page-scroll\">\n";
print "      <a href=\"#Fiction\" class=\"btn btn-circle\">\n";
print "				<i class=\"fa fa-angle-double-down animated\"></i>\n";
print "			</a>\n";
print "    </div>\n";
print "  </section>\n";
print "  <!-- /Section: intro -->\n";
print "  \n";
print "  <!-- Section: Fiction -->\n";
print "  <section id=\"Fiction\" class=\"home-section text-center\">\n";
print "    <div class=\"heading-about\">\n";
print "      <div class=\"container\">\n";
print "        <div class=\"row\">\n";
print "          <div class=\"col-lg-8 col-lg-offset-2\">\n";
print "            <div class=\"wow bounceInDown\" data-wow-delay=\"0.4s\">\n";
print "              <div class=\"section-heading\">\n";
print "                <h2>Fiction Section</h2>\n";
print "                <i class=\"fa fa-2x fa-angle-down\"></i>\n";
print "              </div>\n";
print "			   <!-- photos part --> \n";
print "			  <div class=\"container\">\n";
print "\n";
print "      <div class=\"row\">\n";
print "        <div class=\"col-lg-2 col-lg-offset-5\">\n";
print "          <hr class=\"marginbot-50\">\n";
print "        </div>\n";
print "      </div>\n";
//$q=mysql_query("select * from bookinfo WHERE category='Fiction'");
require_once "./classes/pbook.php";

 $NS= new pbook();
 $cat="Fiction";
 $arr=$NS->select_by_category($cat);
for($i=0;$i<sizeof($arr);$i++)
{
print "      <div class=\"row\">\n";
print "        <div class=\"col-md-3\">\n";
print "          <div class=\"wow bounceInUp\" data-wow-delay=\"0.2s\">\n";
print "            <div class=\"team boxed-grey\">\n";
print "              <div class=\"inner\">\n";
	$id=$row["id"];
	echo "<h5>".$arr[$i][0]."</h5>\n";
	$counter++;
    echo   "<p class=\"subtitle\">By:" .$arr[$i][1]. "</p>\n";
    echo   "<div class=\"avatar\"><img src=\"".$arr[$i][3]."\" alt=\"\" class=\"img-responsive img-circle\" /></div>\n";
	echo   "<div> <a  href=\"".$arr[$i][2]. "\">Read/Download</a></div>\n";	

print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
		
}
//print "      <div class=\"row\">\n";
//print "        <div class=\"col-md-3\">\n";
//print "          <div class=\"wow bounceInUp\" data-wow-delay=\"0.2s\">\n";
//print "            <div class=\"team boxed-grey\">\n";
//print "              <div class=\"inner\">\n";
//print "                <h5>Star Wars</h5>\n";
//print "                <p class=\"subtitle\">By: Eric Johnson</p>\n";
//print "                <div class=\"avatar\"><img src=\"img/team/1.jpg\" alt=\"\" class=\"img-responsive img-circle\" /></div>\n";
//print "              </div>\n";
//print "            </div>\n";
//print "          </div>\n";
//print "        </div>\n";
//print "        <div class=\"col-md-3\">\n";
//print "          <div class=\"wow bounceInUp\" data-wow-delay=\"0.5s\">\n";
//print "            <div class=\"team boxed-grey\">\n";
//print "              <div class=\"inner\">\n";
//print "                <h5>Kingdom of a thousand</h5>\n";
//print "                <p class=\"subtitle\">By: Eftos Ent.</p>\n";
//print "                <div class=\"avatar\"><img src=\"img/team/2.jpg\" alt=\"\" class=\"img-responsive img-circle\" /></div>\n";
//print "			<div> <a  href=\"https://www.bookrix.com/book.html?bookID=eftostunnel_1301049355.0605859756#0,486,95454\">Download</a></div>\n";
//print "\n";
//print "\n";
//print "              </div>\n";
//print "            </div>\n";
//print "          </div>\n";
//print "        </div>\n";
//print "        <div class=\"col-md-3\">\n";
//print "          <div class=\"wow bounceInUp\" data-wow-delay=\"0.8s\">\n";
//print "            <div class=\"team boxed-grey\">\n";
//print "              <div class=\"inner\">\n";
//print "                <h5>Time Traveler</h5>\n";
//print "                <p class=\"subtitle\">By: S. M. Bowes</p>\n";
//print "                <div class=\"avatar\"><img src=\"img/team/3.jpg\" alt=\"\" class=\"img-responsive img-circle\" /></div>\n";
//print "				<div> <a  href=\"https://www.bookrix.com/book.html?bookID=susanbowes_1257178452.5276820660#0,486,8838 \">Download</a></div>\n";
//print "\n";
//print "\n";
//print "              </div>\n";
//print "            </div>\n";
//print "          </div>\n";
//print "        </div>\n";
//print "        <div class=\"col-md-3\">\n";
//print "          <div class=\"wow bounceInUp\" data-wow-delay=\"1s\">\n";
//print "            <div class=\"team boxed-grey\">\n";
//print "              <div class=\"inner\">\n";
//print "                <h5>Unofficial Harry Potter Cookbook</h5>\n";
//print "                <p class=\"subtitle\">By: Dinah Bucholz</p>\n";
//print "                <div class=\"avatar\"><img src=\"img/team/4.jpg\" alt=\"\" class=\"img-responsive img-circle\" /></div>\n";
//print "			<div> <a  href=\"https://www.pdfdrive.com/unofficial-harry-potter-cookbookpdf-e27649946.html\">Download</a></div>\n";
//print "\n";
//print "\n";
//print "              </div>\n";
//print "            </div>\n";
//print "          </div>\n";
//print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "		  <!-- photos part --> \n";
print "		   \n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "    <div class=\"container\">\n";
print "\n";
print "      <div class=\"row\">\n";
print "        <div class=\"col-lg-2 col-lg-offset-5\">\n";
print "          <hr class=\"marginbot-50\">\n";
print "        </div>\n";
print "      </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "  </section>\n";
print "  <!-- /Section: Fiction -->\n";
print "  \n";
print "  <!-- Section: Kids -->\n";
print "  <section id=\"Kids\" class=\"home-section text-center\">\n";
print "    <div class=\"heading-about\">\n";
print "      <div class=\"container\">\n";
print "        <div class=\"row\">\n";
print "          <div class=\"col-lg-8 col-lg-offset-2\">\n";
print "            <div class=\"wow bounceInDown\" data-wow-delay=\"0.4s\">\n";
print "              <div class=\"section-heading\">\n";
print "                <h2>Kids Section</h2>\n";
print "                <i class=\"fa fa-2x fa-angle-down\"></i>\n";
print "			 <!-- photos part --> \n";
print "			  <div class=\"container\">\n";
print "\n";
print "      <div class=\"row\">\n";
print "        <div class=\"col-lg-2 col-lg-offset-5\">\n";
print "          <hr class=\"marginbot-50\">\n";
print "        </div>\n";
print "      </div>\n";
//$q=mysql_query("select * from bookinfo WHERE category='Kids'");
require_once "./classes/pbook.php";

 $NS= new pbook();
 $cat="Kids";
 $arr=$NS->select_by_category($cat);
for($i=0;$i<sizeof($arr);$i++)
{
print "      <div class=\"row\">\n";
print "        <div class=\"col-md-3\">\n";
print "          <div class=\"wow bounceInUp\" data-wow-delay=\"0.2s\">\n";
print "            <div class=\"team boxed-grey\">\n";
print "              <div class=\"inner\">\n";
	$id=$row["id"];
	echo "<h5>".$arr[$i][0]."</h5>\n";
	$counter++;
    echo   "<p class=\"subtitle\">By:" .$arr[$i][1]. "</p>\n";
    echo   "<div class=\"avatar\"><img src=\"".$arr[$i][3]."\" alt=\"\" class=\"img-responsive img-circle\" /></div>\n";
	echo   "<div> <a  href=\"".$arr[$i][2]. "\">Read/Download</a></div>\n";	

print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
		
}
print "      </div>\n";
print "    </div>\n";
print "		  \n";
print "		  <!-- photos part --> \n";
print "\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "    <div class=\"container\">\n";
print "\n";
print "      <div class=\"row\">\n";
print "        <div class=\"col-lg-2 col-lg-offset-5\">\n";
print "          <hr class=\"marginbot-50\">\n";
print "        </div>\n";
print "      </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "  </section>\n";
print "  <!-- /Section: Kids -->\n";
print "  \n";
print "  <!-- Section: History -->\n";
print "  <section id=\"History\" class=\"home-section text-center\">\n";
print "    <div class=\"heading-about\">\n";
print "      <div class=\"container\">\n";
print "        <div class=\"row\">\n";
print "          <div class=\"col-lg-8 col-lg-offset-2\">\n";
print "            <div class=\"wow bounceInDown\" data-wow-delay=\"0.4s\">\n";
print "              <div class=\"section-heading\">\n";
print "                <h2>History Section</h2>\n";
print "                <i class=\"fa fa-2x fa-angle-down\"></i>\n";
print "				 <!-- photos part --> \n";
print "			  <div class=\"container\">\n";
print "\n";
print "      <div class=\"row\">\n";
print "        <div class=\"col-lg-2 col-lg-offset-5\">\n";
print "          <hr class=\"marginbot-50\">\n";
print "        </div>\n";
print "      </div>\n";
//$q=mysql_query("select * from bookinfo WHERE category='History'");


 $NS= new pbook();
 $cat="History";
 $arr=$NS->select_by_category($cat);
for($i=0;$i<sizeof($arr);$i++)
{
print "      <div class=\"row\">\n";
print "        <div class=\"col-md-3\">\n";
print "          <div class=\"wow bounceInUp\" data-wow-delay=\"0.2s\">\n";
print "            <div class=\"team boxed-grey\">\n";
print "              <div class=\"inner\">\n";
	$id=$row["id"];
	echo "<h5>".$arr[$i][0]."</h5>\n";
	$counter++;
    echo   "<p class=\"subtitle\">By:" .$arr[$i][1]. "</p>\n";
    echo   "<div class=\"avatar\"><img src=\"".$arr[$i][3]."\" alt=\"\" class=\"img-responsive img-circle\" /></div>\n";
	echo   "<div> <a  href=\"".$arr[$i][2]. "\">Read/Download</a></div>\n";	

print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
		
}

print "    </div>\n";
print "		  \n";
print "		  <!-- photos part --> \n";
print "\n";
print "\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "    <div class=\"container\">\n";
print "\n";
print "      <div class=\"row\">\n";
print "        <div class=\"col-lg-2 col-lg-offset-5\">\n";
print "          <hr class=\"marginbot-50\">\n";
print "        </div>\n";
print "      </div>\n";
print "     \n";
print "        </div>\n";
print "       \n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "  </section>\n";
print "  <!-- /Section: History -->\n";
print "  <!-- Section: Horror -->\n";
print "  <section id=\"Horror\" class=\"home-section text-center\">\n";
print "    <div class=\"heading-about\">\n";
print "      <div class=\"container\">\n";
print "        <div class=\"row\">\n";
print "          <div class=\"col-lg-8 col-lg-offset-2\">\n";
print "            <div class=\"wow bounceInDown\" data-wow-delay=\"0.4s\">\n";
print "              <div class=\"section-heading\">\n";
print "                <h2>Horror Section</h2>\n";
print "                <i class=\"fa fa-2x fa-angle-down\"></i>\n";
print "						 <!-- photos part --> \n";
print "			  <div class=\"container\">\n";
print "\n";
print "      <div class=\"row\">\n";
print "        <div class=\"col-lg-2 col-lg-offset-5\">\n";
print "          <hr class=\"marginbot-50\">\n";
print "        </div>\n";
print "      </div>\n";
//$q=mysql_query("select * from bookinfo WHERE category='Horror'");


 $NS= new pbook();
 $cat="Horror";
 $arr=$NS->select_by_category($cat);
for($i=0;$i<sizeof($arr);$i++)
{
print "      <div class=\"row\">\n";
print "        <div class=\"col-md-3\">\n";
print "          <div class=\"wow bounceInUp\" data-wow-delay=\"0.2s\">\n";
print "            <div class=\"team boxed-grey\">\n";
print "              <div class=\"inner\">\n";
	$id=$row["id"];
	echo "<h5>".$arr[$i][0]."</h5>\n";
	$counter++;
    echo   "<p class=\"subtitle\">By:" .$arr[$i][1]. "</p>\n";
    echo   "<div class=\"avatar\"><img src=\"".$arr[$i][3]."\" alt=\"\" class=\"img-responsive img-circle\" /></div>\n";
	echo   "<div> <a  href=\"".$arr[$i][2]. "\">Read/Download</a></div>\n";	

print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
		
}
print "    </div>\n";
print "		  \n";
print "		  <!-- photos part --> \n";
print "\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "    <div class=\"container\">\n";
print "\n";
print "      <div class=\"row\">\n";
print "        <div class=\"col-lg-2 col-lg-offset-5\">\n";
print "          <hr class=\"marginbot-50\">\n";
print "        </div>\n";
print "      </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "  </section>\n";
print "  <!-- /Section: Horror -->\n";
print "  <!-- Section: Romance -->\n";
print "  <section id=\"Romance\" class=\"home-section text-center\">\n";
print "    <div class=\"heading-about\">\n";
print "      <div class=\"container\">\n";
print "        <div class=\"row\">\n";
print "          <div class=\"col-lg-8 col-lg-offset-2\">\n";
print "            <div class=\"wow bounceInDown\" data-wow-delay=\"0.4s\">\n";
print "              <div class=\"section-heading\">\n";
print "                <h2>Romance Section</h2>\n";
print "                <i class=\"fa fa-2x fa-angle-down\"></i>\n";
print "						 <!-- photos part --> \n";
print "			  <div class=\"container\">\n";
print "\n";
print "      <div class=\"row\">\n";
print "        <div class=\"col-lg-2 col-lg-offset-5\">\n";
print "          <hr class=\"marginbot-50\">\n";
print "        </div>\n";
print "      </div>\n";
//$q=mysql_query("select * from bookinfo WHERE category='Romance'");


 $NS= new pbook();
 $cat="Romance";
 $arr=$NS->select_by_category($cat);
for($i=0;$i<sizeof($arr);$i++)
{
print "      <div class=\"row\">\n";
print "        <div class=\"col-md-3\">\n";
print "          <div class=\"wow bounceInUp\" data-wow-delay=\"0.2s\">\n";
print "            <div class=\"team boxed-grey\">\n";
print "              <div class=\"inner\">\n";
	$id=$row["id"];
	echo "<h5>".$arr[$i][0]."</h5>\n";
	$counter++;
    echo   "<p class=\"subtitle\">By:" .$arr[$i][1]. "</p>\n";
    echo   "<div class=\"avatar\"><img src=\"".$arr[$i][3]."\" alt=\"\" class=\"img-responsive img-circle\" /></div>\n";
	echo   "<div> <a  href=\"".$arr[$i][2]. "\">Read/Download</a></div>\n";	

print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
		
}

print "    </div>\n";
print "		  \n";
print "		  <!-- photos part --> \n";
print "\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "    <div class=\"container\">\n";
print "\n";
print "      <div class=\"row\">\n";
print "        <div class=\"col-lg-2 col-lg-offset-5\">\n";
print "          <hr class=\"marginbot-50\">\n";
print "        </div>\n";
print "      </div>\n";
print "     \n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "  </section>\n";
print "  <!-- /Section: Romance -->\n";
print "  \n";
print "  <!-- Section: Arts -->\n";
print "  <section id=\"Arts\" class=\"home-section text-center\">\n";
print "    <div class=\"heading-about\">\n";
print "      <div class=\"container\">\n";
print "        <div class=\"row\">\n";
print "          <div class=\"col-lg-8 col-lg-offset-2\">\n";
print "            <div class=\"wow bounceInDown\" data-wow-delay=\"0.4s\">\n";
print "              <div class=\"section-heading\">\n";
print "                <h2>Arts Section</h2>\n";
print "                <i class=\"fa fa-2x fa-angle-down\"></i>\n";
print "						 <!-- photos part --> \n";
print "			  <div class=\"container\">\n";
print "\n";
print "      <div class=\"row\">\n";
print "        <div class=\"col-lg-2 col-lg-offset-5\">\n";
print "          <hr class=\"marginbot-50\">\n";
print "        </div>\n";
print "      </div>\n";
//$q=mysql_query("select * from bookinfo WHERE category='Arts'");


 $NS= new pbook();
 $cat="Arts";
 $arr=$NS->select_by_category($cat);
for($i=0;$i<sizeof($arr);$i++)
{
print "      <div class=\"row\">\n";
print "        <div class=\"col-md-3\">\n";
print "          <div class=\"wow bounceInUp\" data-wow-delay=\"0.2s\">\n";
print "            <div class=\"team boxed-grey\">\n";
print "              <div class=\"inner\">\n";
	$id=$row["id"];
	echo "<h5>".$arr[$i][0]."</h5>\n";
	$counter++;
    echo   "<p class=\"subtitle\">By:" .$arr[$i][1]. "</p>\n";
    echo   "<div class=\"avatar\"><img src=\"".$arr[$i][3]."\" alt=\"\" class=\"img-responsive img-circle\" /></div>\n";
	echo   "<div> <a  href=\"".$arr[$i][2]. "\">Read/Download</a></div>\n";	

print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
		
}

print "    </div>\n";
print "		  \n";
print "		  <!-- photos part --> \n";
print "\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "    <div class=\"container\">\n";
print "\n";
print "      <div class=\"row\">\n";
print "        <div class=\"col-lg-2 col-lg-offset-5\">\n";
print "          <hr class=\"marginbot-50\">\n";
print "        </div>\n";
print "      </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "  </section>\n";
print "  <!-- /Section: Arts -->\n";
print "  \n";
print "\n";
print "  <footer>\n";
print "    <div class=\"container\">\n";
print "      <div class=\"row\">\n";
print "        <div class=\"col-md-12 col-lg-12\">\n";
print "          <div class=\"wow shake\" data-wow-delay=\"0.4s\">\n";
print "            <div class=\"page-scroll marginbot-30\">\n";
print "              <a href=\"#intro\" id=\"totop\" class=\"btn btn-circle\">\n";
print "							<i class=\"fa fa-angle-double-up animated\"></i>\n";
print "						</a>\n";
print "            </div>\n";
print "          </div>\n";
print "          <p>©Yomna Yamana Hanaa.</p>\n";
print "          <div class=\"credits\">\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "  </footer>\n";
print "\n";
print "  <!-- Core JavaScript Files -->\n";
print "  <script src=\"js/jquery.min.js\"></script>\n";
print "  <script src=\"js/bootstrap.min.js\"></script>\n";
print "  <script src=\"js/jquery.easing.min.js\"></script>\n";
print "  <script src=\"js/jquery.scrollTo.js\"></script>\n";
print "  <script src=\"js/wow.min.js\"></script>\n";
print "  <!-- Custom Theme JavaScript -->\n";
print "  <script src=\"js/custom.js\"></script>\n";
print "  <script src=\"contactform/contactform.js\"></script>\n";
print "\n";
print "</body>\n";
print "\n";
print "</html>\n";

?>
